BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        on_press: app.handle_clear()
    TextInput:
        id: input_name
        text: ''
        multiline: False
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)
    Label:
        id: output_label
        text: ''
        color: (1, 1, 0, 1)