BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
            font_size: 48
            multiline: False
            input_filter: 'float'
        Button:
            text: 'Square'
            # the following line specifies the function in the app class to call when the button is pressed
            on_press: app.handle_calculate(input_number.text)

        Label:
            id: output_label
            text: ''
            font_size: 48
            color: (1, 0.4, 0.7, 1)

    Label:
        text: 'Enter a number and press "Square"'
        text_size: self.width, None
        height: 30
        halign: 'center'
        valign: 'middle'
